### ISSUE TITLE
MSI: Cannot launch worker process when a key with non-ASCII character exists just under `SOFTWARE/Microsoft/Windows/CurrentVersion/Uninstall/` registry

### ISSUE THREAD

**Issue by tbs575** [fluent/fluent-package-builder#616]
### Describe the bug

I am newbie. met error for log file with chinese character

### To Reproduce

- Installed td-agent 4.5
- change config file 
- run command `td-agent -c etc\td-agent\td-agent.conf`
- met error

sample log content:
```
[2023:06:13 00:00:00][INFO]请求:{"Parkcode":"510105037"}
[2023:06:13 00:00:00][INFO]返回:{"State":0,"Desc":"成功","Result":[{"num":"2032","garagecode":"1"}]}
[2023:06:13 00:00:00][INFO]开时校时...
```

### Expected behavior

how to fixed?

### Your Environment

```markdown
- Fluentd version:
- TD Agent version: 4.5
- Operating system: Windows 10
- Kernel version:
```

### Your Configuration

```apache
<source>
  @type tail
  path d:\test\logs\*.log
  tag apache.access
  encoding UTF-8
  from_encoding UTF-8
  <parse>
    @type apache2
  </parse>
  <storage>
    @type local
    persistent true
    path C:\opt\td-agent\winlog.json
  </storage>
</source>

<match winevt.raw>
  @type stdout
</match>
```

### Your Error Log

```shell
2023-06-14 16:40:40 +0800 [info]: init supervisor logger path=nil rotate_age=nil rotate_size=nil
2023-06-14 16:40:40 +0800 [info]: parsing config file is succeeded path="etc\\td-agent\\td-agent.conf"
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-calyptia-monitoring' version '0.1.3'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-elasticsearch' version '5.3.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-flowcounter-simple' version '0.1.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-kafka' version '0.19.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-metrics-cmetrics' version '0.1.2'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-opensearch' version '1.1.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-parser-winevt_xml' version '0.2.5'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-prometheus_pushgateway' version '0.1.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-record-modifier' version '2.1.1'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.4.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-s3' version '1.7.2'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-sd-dns' version '0.1.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-td' version '1.2.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-webhdfs' version '1.5.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-windows-eventlog' version '0.8.3'
2023-06-14 16:40:40 +0800 [info]: gem 'fluent-plugin-windows-exporter' version '1.0.0'
2023-06-14 16:40:40 +0800 [info]: gem 'fluentd' version '1.16.1'
2023-06-14 16:40:40 +0800 [warn]: 'pos_file PATH' parameter is not set to a 'tail' source.
2023-06-14 16:40:40 +0800 [warn]: this parameter is highly recommended to save the position to resume tailing.
2023-06-14 16:40:40 +0800 [warn]: 'encoding' and 'from_encoding' are same encoding. No effect
2023-06-14 16:40:40 +0800 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    path "d:\\test\\logs\\*.log"
    tag "apache.access"
    encoding "UTF-8"
    from_encoding "UTF-8"
    <parse>
      @type "apache2"
      unmatched_lines
    </parse>
    <storage>
      @type local
      persistent true
      path C:\opt\td-agent\winlog.json
    </storage>
  </source>
  <match winevt.raw>
    @type stdout
  </match>
</ROOT>
2023-06-14 16:40:40 +0800 [info]: starting fluentd-1.16.1 pid=6432 ruby="2.7.8"
2023-06-14 16:40:40 +0800 [info]: spawn command to main:  cmdline=["C:/opt/td-agent/bin/ruby.exe", "-Eascii-8bit:ascii-8bit", "C:/opt/td-agent/bin/fluentd", "-c", "etc\\td-agent\\td-agent.conf", "--under-supervisor"]
Traceback (most recent call last):
        17: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        16: from <internal:gem_prelude>:1:in `require'
        15: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems.rb:1427:in `<top (required)>'
        14: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems.rb:1427:in `require'
        13: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:24:in `<top (required)>'
        12: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        11: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:125:in `enable_dll_search_paths'
        10: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:115:in `mingw_bin_path'
         9: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:102:in `msys_path'
         8: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:68:in `iterate_msys_paths'
         7: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:68:in `each'
         6: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:70:in `block in iterate_msys_paths'
         5: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:542:in `open'
         4: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:435:in `open'
         3: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:71:in `block (2 levels) in iterate_msys_paths'
         2: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:611:in `each_key'
         1: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:910:in `export_string'
C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:910:in `encode': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
2023-06-14 16:40:41 +0800 [error]: Worker 0 exited unexpectedly with status 1
Traceback (most recent call last):
        17: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        16: from <internal:gem_prelude>:1:in `require'
        15: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems.rb:1427:in `<top (required)>'
        14: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems.rb:1427:in `require'
        13: from C:/opt/td-agent/lib/ruby/2.7.0/rubygems/defaults/operating_system.rb:24:in `<top (required)>'
        12: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
        11: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:125:in `enable_dll_search_paths'
        10: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:115:in `mingw_bin_path'
         9: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:102:in `msys_path'
         8: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:68:in `iterate_msys_paths'
         7: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:68:in `each'
         6: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:70:in `block in iterate_msys_paths'
         5: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:542:in `open'
         4: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:435:in `open'
         3: from C:/opt/td-agent/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:71:in `block (2 levels) in iterate_msys_paths'
         2: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:611:in `each_key'
         1: from C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:910:in `export_string'
C:/opt/td-agent/lib/ruby/2.7.0/win32/registry.rb:910:in `encode': U+767E to ASCII-8BIT in conversion from UTF-16LE to UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
2023-06-14 16:40:41 +0800 [error]: Worker 0 exited unexpectedly with status 1
```

**Comment by ashie** [comment]
I want to fix it in upstream, but I'm not sure where should be report it to yet.

The codes which causes this issue:

RubyInstaller2:
* https://github.com/oneclick/rubyinstaller2/blob/898188c555acacbc81141adda73d361922fd1f72/lib/ruby_installer/build/msys2_installation.rb#L75

Ruby:
* https://github.com/ruby/ruby/blob/038189b61f60e27ea081817979cb7a043bcf5798/ext/win32/lib/win32/registry.rb#L611
* https://github.com/ruby/ruby/blob/038189b61f60e27ea081817979cb7a043bcf5798/ext/win32/lib/win32/registry.rb#L906-L908

In addition, we should add work around for this issue until it's addressed in upstream.
Probably we can apply a patch to RubyInstaller by the following code:
https://github.com/fluent/fluent-package-builder/blob/7e637b37665f7fa739693351c4960c290a5e6c29/fluent-package/config.rb#L38-L44
It would be better to treat only MSYS2 which is installed under `C:\opt\fluent`, it can be realized easily by adding `return` [here](https://github.com/oneclick/rubyinstaller2/blob/898188c555acacbc81141adda73d361922fd1f72/lib/ruby_installer/build/msys2_installation.rb#L60).
